### ISSUE TITLE
Relationship cache causes unexpected behaviour

### ISSUE THREAD

**Issue by bernardeli** [excid3/acts_as_tenant#6]
Hi @excid3, thanks for forking it and taking a stab on maintaining acts_as_tenant.

I introduced tenancy to an app early this year and have encountered unexpected behaviour due to this override: 

https://github.com/excid3/acts_as_tenant/blob/master/lib/acts_as_tenant/model_extensions.rb#L177-L183

The gains are negligible, less than 0.5ms, and ActiveRecord caches that if we're calling the tenant object over and over with the same object.

If the tenant object changed/updated underneath between when it was first loaded to when the association is called, it causes to return a stale object. That's pretty much what I've hit a few times until forking and dropping these lines: https://github.com/fivegoodfriends/acts_as_tenant/commit/33ac6cfee2e339f3883cdd945e0df00297ff959d

By letting `belongs_to` work as intended, it hits the db, taking less than 0.5ms, and AR caches it for free after that.

At the time I wrote the initial [issue](https://github.com/ErwinM/acts_as_tenant/issues/226) at ErwinM's repo, I didn't find the reason behind the caching through looking commit history.

Is there a real need for it you may be aware of?
Would you consider accepting a PR that drops it?
I'd be happy to do the work.

I appreciate your help and time.

**Comment by excid3** [comment]
I haven't looked at this piece yet. Looks like the main reason is to make the tenant immutable so that you don't accidentally change it. I don't see why that would need to override the getter.

It seems unnecessary, so I'd be happy to see a PR for this. Let's just make sure we have a test for the unexpected behavior so we can reference that. 👍

If anyone knows why the getter override is there, please let us know!
